### ISSUE TITLE
Internationalization (i18n)

### ISSUE THREAD

**Issue by hytalo-bassi** [victorcebarros/korone#1]
Give support to other languages is very important. So, how could the bot be internationalized?

Using a platform for translations, like [Crowdin](https://crowdin.com/), or using locale-related files (en_US, pt_BR) in the yaml or json extension?

Using an i18n JSON it could look like this:

```
// en_US
{
    "hello": "Hey {name}! How are you?"
    ... 
}

// pt_BR

{
   "hello": "Olá {nome}! Como vai?"
   ...
}
```

**Comment by victorcebarros** [comment]
I haven't been assiduously for solutions to this problem yet. However, I believe I will use YAML specifically to store the translations and Crowdin to allow others to contribute with translations.

If you go through PyKorone's source code, you will see they use Crowdin for such purposes, perhaps expect something similar.

**Comment by victorcebarros** [comment]
I rebased your commits into the 'master' branch. It's a good starting point. I will work on this feature after I finish working with the database module.
